version: 1.0
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s -  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: pipeline.log
root:
  level: DEBUG
  handlers: [file, console]